<CustButton@Button>:
    font_size: 32
    color: 0, 0, 0, 1
    size: 150, 50
    background_normal: ''
    background_down: 'File_Grey.png'
    background_color: .99, .88, .88, 1
    size_hint: .4, .3
    
<FloatLayout>:
	CustButton:
		text: "Random"
		pos_hint: {"x":0, "top":1}
		
	CustButton:
		text: "Button"
		pos_hint: {"x":0, "top":1}
		
	CustButton:
		text: "Random"
		pos_hint: {"x":0, "top":1}
		
	